apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: leemah12/leemah-store
...
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-srv
spec:
  selector:
    app: react-app
  ports:
    - name: my-app
      port: 3000
      targetPort: 3000
  type: NodePort

